version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:2025.04
    working_directory: /home/circleci/project

jobs:
  build-docker-image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install GitHub CLI
          command: |
            # Check if gh is already installed
            if ! command -v gh &> /dev/null; then
              # Download and install gh
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
              sudo apt update
              sudo apt install gh
            fi
      - run:
          name: Build Docker image
          command: |
            docker login -u cn-north-1@WS69AVPZCUMA3YMNFWHD -p 0c05b6ee08f62336ccaff8c335ac6987136f970a3da2e248aa7ff2d3d1e8401e swr.cn-north-1.myhuaweicloud.com
            docker build -t swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest .
      - run:
          name: Package image
          command: |
            docker save -o worker.tar swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest
            mkdir xinfan-poc-master
            mv worker.tar xinfan-poc-master
            mv master-image.sh xinfan-poc-master
            mv armor-poc-worker.yaml xinfan-poc-master
            XZ_OPT=-9 tar -cJvf xinfan-poc-master.tar.xz xinfan-poc-master
      - run:
          name: Release package
          command: |
            gh auth login --with-token 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
            VERSION=$(date +'%Y.%m.%d')
            gh release create "v$VERSION" xinfan-poc-master.tar.xz --title "Release v$VERSION" --notes "自动发布的 Release"
      - run:
          name: Push Docker image
          command: |
            docker push swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest

workflows:
  version: 2
  build:
    jobs:
      - build-docker-image