version: 2.1
executors:
  python-executor:
    docker:
      - image: python:3.9-slim
    working_directory: /home/forcloud
jobs:
  build-docker-image:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: pip install paramiko pexpect requests PyYAML -i https://pypi.mirrors.ustc.edu.cn/simple
      - run:
          name: Move kubectl
          command: mv /home/forcloud/kubectl /usr/bin
      - run:
          name: Install netcat
          command: |
            dpkg -i /home/forcloud/netcat-traditional_1.10-41.1_amd64.deb && rm -f /home/forcloud/netcat-traditional_1.10-41.1_amd64.deb
workflows:
  version: 2
  build:
    jobs:
      - build-docker-image