version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:2025.07
    working_directory: /home/circleci/project

jobs:
  build-docker-image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install GitHub CLI
          command: |
            # Check if gh is already installed
            if ! command -v gh &> /dev/null; then
              # Download and install gh
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
              sudo apt update
              sudo apt install gh
            fi
      - run:
          name: Permissions for k8s tools
          command: |
            sudo chmod +x kubectl
      - run:
          name: Build Docker image
          command: |
            docker login -u cn-north-1@WS69AVPZCUMA3YMNFWHD -p 0c05b6ee08f62336ccaff8c335ac6987136f970a3da2e248aa7ff2d3d1e8401e swr.cn-north-1.myhuaweicloud.com
            docker buildx create --use --name mybuilder
            docker buildx inspect --bootstrap
            docker buildx build --platform linux/amd64,linux/arm64 -t swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest --push .
      - run:
          name: Package image
          command: |
            docker tag swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest core.harbor.safedog.site/armorpoc20240512/armor_poc_worker:latest
            docker save -o worker.tar core.harbor.safedog.site/armorpoc20240512/armor_poc_worker:latest
            mkdir xinfan-poc-master
            mv worker.tar xinfan-poc-master
            mv master-image.sh xinfan-poc-master
            mv armor-poc-worker.yaml xinfan-poc-master
            XZ_OPT=-9 tar -cJvf xinfan-poc-master.tar.xz xinfan-poc-master
      - run:
          name: GitHub authentication
          command: |
            export GH_AUTH_SKIP_MFA=true
            echo "${GITHUB_TOKEN}" | gh auth login --with-token
      - run:
          name: Git release 
          command: |
            VERSION=$(date +'%Y.%m.%d.%H.%M')
            gh release create "v$VERSION" --title "Release v$VERSION" --notes "CNAPP信帆POC镜像包 Release" xinfan-poc-master.tar.xz
      - run:
          name: Push Docker image
          command: |
            docker push swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest

workflows:
  version: 2
  build:
    jobs:
      - build-docker-image