version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:latest
    working_directory: /home/forcloud
jobs:
  build-docker-image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker login -u cn-north-1@WS69AVPZCUMA3YMNFWHD -p 0c05b6ee08f62336ccaff8c335ac6987136f970a3da2e248aa7ff2d3d1e8401e swr.cn-north-1.myhuaweicloud.com
            docker build -t swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest .
      - run:
          name: Push Docker image
          command: |
            docker push swr.cn-north-1.myhuaweicloud.com/armor-poc-test/armor_poc_worker:latest
workflows:
  version: 2
  build:
    jobs:
      - build-docker-image