apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dvwa-target
  name: dvwa-target-deployment
  namespace: xinfan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-target
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dvwa-target
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeSetcontainer
                operator: In
                values:
                - cloudarmortest
      containers:
      - command:
        - /bin/bash
        - -ce
        - tail -f /dev/null
        image: core.harbor.safedog.site/armorpoc20240512/armor_dvwa:latest
        imagePullPolicy: IfNotPresent
        name: dvwa-target
        securityContext:
          privileged: true
          runAsUser: 0
      imagePullSecrets:
      - name: harbor-secret
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/disk-pressure
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/pid-pressure
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/network-unavailable
        operator: Exists
